spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/q37232377
    username: postgres
    password: forever
  jpa:
    database: postgresql
#    database-platform: POSTGRESQL
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true



#spring.jpa.database=POSTGRESQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.database.driverClassName=org.postgresql.Driver
#spring.datasource.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/blood
#spring.datasource.username=postgres
#spring.datasource.password=postgres